Add push functionality to CDS Handler
transifex/transifex-swift pull request #9
Opened 2020-12-02 11:20 UTC by stelabouras

Adds functionality to push base translations to CDS by introducing the
`pushTranslations()` method in `TxNative`, `NativeCore` and `CDSHandler`
classes.

Alongside this method, the `TxTranslationUnit` class is also introduced
which offers a way for both Swift and Objective-C projects to construct
the data structure that will hold all the necessary information for the
strings to be pushed. The `TxTranslationUnit` also offers an internal
method that transforms the object to the `Codable` `SourceString` struct
that can be used when constructing the data to be pushed.

This commit also moves the `occurencies` property from `SourceString`
struct to `SourceString` meta, where it should have been originally
placed.

The `pushTranslations()` method of `CDSHandler` serializes the passed
array of `TxTranslationUnit` objects using an internal `PushData` struct
and the resulting `Data` object is passed to the `URLRequest` that is
used to push the strings to CDS. An extra optional `purge` parameter can
also be used to replace the entire resource content, if needed.

When the push logic completes, a completion handler informs the caller
asynchronously on whether the request was successful or not.

Finally this commit removes a couple of unused `;` characters.

2020-12-06 22:11 UTC, dbendilas requested changes
Looks great. I have a question about `TxTranslationUnit`, the rest of my comments are trivial.

2020-12-07 07:23 UTC, stelabouras commented on Sources/TransifexNative/CDSHandler.swift
> +                                 _ purge: Bool = false,
Done!

2020-12-07 07:23 UTC, stelabouras commented on Sources/TransifexNative/SourceString.swift
> +    let occurencies: [String]
Good catch, fixed!

2020-12-07 07:25 UTC, stelabouras commented on Sources/TransifexNative/SourceString.swift
> +public class TxTranslationUnit: NSObject {
`SourceString` is a Swift struct that conforms to the `Codable` protocol for JSON serialization / deserialization, so we can't use it on Objective-C projects.

I wanted to keep the functionality of that `Codable` struct internally, but offer a way for both Swift / Objective-C projects to pass the translation units to the SDK.

I am open to other suggestions though!

2020-12-10 08:22 UTC, dbendilas approved these changes

2020-12-10 08:22 UTC, merged